site_name: pyTRIS

theme:
  name: material
  icon:
    logo: fontawesome/solid/tachometer-alt
    repo: fontawesome/brands/github-alt

markdown_extensions:
  - toc:
      permalink: true
  # - pymdownx.highlight:
  #     use_pygments: true
  #     linenums: true
  - markdown.extensions.codehilite

plugins:
  - search

repo_name: asongtoruin/pyTRIS
repo_url: https://github.com/asongtoruin/pyTRIS

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Endpoints: endpoints.md